### ISSUE TITLE
When creating a new template, saving key does not always save it.

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#19]

**Comment by shengb** [comment]
We found that it seems to be easier to reproduce this issue with 2 or more text input fields for a new template.

**Comment by dongliu** [comment]
I could not reproduce this. 
Please specify in what browser version, and detailed procedure to reproduce. 
When an input's spec is open (the done button is seen on screen), the user cannot save it, and a modal will appear to tell the user to confirm the spec first in order to avoid losing any update. 
This is the designed experience. I know some IE version has issue with the modal. 
<img width="739" alt="screen shot 2018-09-08 at 2 23 11 pm" src="https://user-images.githubusercontent.com/599397/45258778-00278100-b373-11e8-8897-a70a8bc49730.png">
<img width="744" alt="screen shot 2018-09-08 at 2 23 25 pm" src="https://user-images.githubusercontent.com/599397/45258779-03bb0800-b373-11e8-9bf4-b430551ccc84.png">
A user should always see a message on top when the template is saved successfully or failed.

**Comment by shengb** [comment]
Tried a few times with Chrome, and did not see the problem.
It seems to happen in Firefox. I am using version 60.1.0esr (64-bit).
Will try to update my Firefox version to double check it.

**Comment by shengb** [comment]
I attached a screen shot to show it. It does not always fail, as you can see from this demo.
[traveler_user_key_demo.zip](https://github.com/AdvancedPhotonSource/traveler/files/2367223/traveler_user_key_demo.zip)

**Comment by dongliu** [comment]
I reproduced it on my local with a firefox. The problem is not on server side, it is on client side. When you choose a value in the user key input from browser suggested text string, the user key is not set in the html, and therefore will not be saved on the server side. working on the fix.
