### ISSUE TITLE
Cannot save for traveler form released

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#198]
For a released form, when generating a step number, there is no mechanism to save the generated step numbers.

**Comment by shengb** [comment]
As there is no real regular form with status, it is not a real issue.

**Comment by dongliu** [comment]
yes, released form does not allow edit. so save as and then start from the new form. 

While check this, I found an issue that is created by the change for https://github.com/AdvancedPhotonSource/traveler/issues/184

The issue is that the jq ajax cannot handle 301/redirect properly such that no redirection happens and the url in the message is `null` . This was at least the behavior on chrome. 

I fixed it in  https://github.com/AdvancedPhotonSource/traveler/pull/201/files
@iTerminate please check if it breaks something you tried to fix.

**Comment by dongliu** [comment]
given all the changes we have made since we filed this issue, I do not think we should fix it. The users can work around this: 
1. create a clone template from the release one;
2. add step numbers to the cloned template;
3. release the cloned template;
4. archive the old released one without number; 


We used to have a way to update the template in an existing traveler with `views/form-manager.jade` and `views/discrepancy-form-manager.jade`. They are cleaned out in https://github.com/AdvancedPhotonSource/traveler/pull/224/files , and therefore no longer available.
