### ISSUE TITLE
Traveler progress update

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#58]
There are 2 bugs to keep traveler progress updated:
1. When I update a traveler and navigate to the binder list, the progress wont update until I navigate to the particular binder;
2. When I navigate to a binder and go to a traveler and update the traveler. Going back does not update the progress, I need to hit refresh.

**Comment by shengb** [comment]
This bug is a left over from the card of progress summary reports: "Eliminate the need to refresh the browser ...".
Mark that card as Done, closing it with this bug report .

**Comment by dongliu** [comment]
The case 1 is a known issue. Case 2 should be fixed in a simple change. 
 
The current logic related to updating progress is
When new data is saved for a traveler, the traveler's progress will be updated. 
When the work list of a binder is retrieved, the binder's progress will be updated. 

Such a design aims to lower the impact of updating a traveler to the minimum. 

If we want the binder progress will be updated when any of its traveler's progress got updated, then there can be a performance impact on the application. Basically, if a traveler is included in *k* binders, then each traveler data update can result *k* extra binder document updates. 

However, I will work on a cascading style of updating binder's progress.
