### ISSUE TITLE
User-entered data can then be retrieved via the keys

### ISSUE THREAD

**Issue by dongliu** [AdvancedPhotonSource/traveler#74]
[Separate from big card.]
- [x] User-entered data can then be retrieved via the keys
- [ ] Functionality has been verified.
**[Note]: It currently returns traveler(s), but without data.**

**Comment by dongliu** [comment]
please check endpoint like `/travelers/:id/keyvalue/json`, it contains the key-value pairs beside other system defined key-value pairs.

**Comment by shengb** [comment]
Any example with for example curl?
It returns a traveler in raw format, but did not see /keyvalue/json.

**Comment by dongliu** [comment]
it was in the web application. added into api in https://github.com/AdvancedPhotonSource/traveler/pull/81

**Comment by dongliu** [comment]
try `https://localhost:3443/apis/travelers/:id/keyvalue/`

**Comment by shengb** [comment]
Good. It works.

**Comment by iTerminate** [comment]
The json should contain a key called keyvalue. Example:
{
'title': 'title'
'status': 1
keyvalue: 
    {
        'key': 'value'
        'key2': 'value2'
    }
}

The problem is, currently I can override system keys by using the same keys in the traveler. I was able to get the output as shown below:
{
  "id": "I just typed this id",
  "title": "3",
  "status": "My own STatus",
  "tags": [],
  "devices": [],
  "testxzcgds_sadf": "2",
  "1st": "sdg",
  "2nd": true
}

**Comment by dongliu** [comment]
good catch, will fix it.

**Comment by dongliu** [comment]
fixed in https://github.com/AdvancedPhotonSource/traveler/pull/82

**Comment by iTerminate** [comment]
Looks Great! Thank You!
